### PR TITLE
Fix migrations for Django 1.11.

### PR DESCRIPTION
**Pull request by benkonrath**
I'm not sure if this is the correct thing to do but it does stop the migrations from being generated in the fluent-pages app.

### CODE REVIEW

**Comment by benkonrath** [comment]
Looks like this only works for Django 1.11 since `default_manager_name` is new in 1.11. I suppose there's a different migration that will be generated for versions < 1.11. I'm not sure how to solve this generally.

**Comment by vdboor** [comment]
Thanks @benkonrath for bringing this to my attention!

I'm afraid this needs to be fixed using some optional kwargs, e.g.

```
if django.VERSION >= (1, 11):
    manager_kwargs = dict(
        managers=[
                ('objects', models.manager.Manager()),
                ('base_objects', models.manager.Manager()),
        ]
    )
else:
    manager_kwargs = {}
```

**Comment by benkonrath** [comment]
Thanks @vdboor. I'm not sure where the `urlnode_extra_options` should go. Can you point me in the right direction so that I can update this PR?

**Comment by benkonrath** [comment]
I think my latest commit is the proper solution. it looks like the managers are working in the fluent pagetypes in django >= 1.10. Without this, the admin pages don't load correctly for flatpage which I'm using in a project.

I wasn't able to get this to work for text page - the test I tried had some errors that I didn't know how to solve. I'm not using textpage so I thought I'd send this PR in now and maybe you can try to get the manager for test page working like I've done with the other pagetypes.

**Comment by vdboor** [comment]
Thanks a lot! I've merged your changes in a slightly different way in 5b1afadd06e222147fd24d998dbb1d1aee656fdc and dea4d10724a9d6df55c154e0f095490338e548a9

**Pull request closed without merging**
