### PR TITLE
Update appsettings.py

### PR DESCRIPTION
**Pull request by deddokatana**
added windows support at line 44, by adding the windows file system notation for the cleaning up the path string check. 

tested and working on windows 7! :D

### CODE REVIEW

**Comment by deddokatana** [comment]
was using windows 7 , python 3.5 and django 1.9, but the issue isnt really a django one. and it builds under py 3.3 and django 1.8 so, its a pass for me :D

**Comment by vdboor** [comment]
AFAIK, for cross-platform support, it's recommended to use forward slashes in Python everywhere..
Secondly, if you really need this, use `os.path.sep` instead of the OS detection.

**Comment by deddokatana** [comment]
it makes sense, and this package was failing giving me errors, so yes it needs to be done. do you want to do the `os.path.sep` or shall i?

**Comment by vdboor** [comment]
@deddokatana, yes if you need this change, please provide a PR to use `os.path.sep` instead.
However, first please try to use forward slashes in your `TEMPLATE_DIRS` / `TEMLATES[..]['DIRS']` setting. While this package may be very verbose when it comes to these errors (and raise the exception first), other packages might silently be affected too.

**Comment by deddokatana** [comment]
will fix and close this pull..

**Comment by vdboor** [comment]
FYI, I've added use of `os.path.sep` in 46e529bb2ed9be68808ed3fbedbc97fec4faee55

**Pull request closed without merging**
